### ISSUE TITLE
Doesn't work with SET_NULL

### ISSUE THREAD

**Issue by professorhaseeb** [scoursen/django-softdelete#70] opened 2020-09-18 21:18 UTC
`SoftDeleteObject` does not respect `SET_NULL`. if I delete an object that is `SET_NULL` on another object. it still deletes that object.

```python
# recreation of the error

class ModelAAA(SoftDeleteObject, models.Model):
    id = models.CharField(default=randomString, max_length=255, primary_key=True)

class ModelBBB(SoftDeleteObject, models.Model):
    id = models.CharField(default=randomString, max_length=255, primary_key=True)
    parent = models.ForeignKey(ModelAAA, on_delete=models.SET_NULL, null=True, blank=True)

# ---
# this below line will also delete ModelBBB object
ModelAAA.objects.filter(id=123).delete()
```

**Comment by mirekdlugosz** [comment] 2020-12-31 03:27
I believe this is effectively duplicate of (not resolved) #45 .

Looking at code, `SoftDeleteObject` tries *very* hard to mimic CASCADE behavior, going out of its way to delete related values, ignoring multiple exceptions along the way. I found two possible entry points to override this behavior:

1. `self._do_delete(changeset, related)` will be called during soft deletion for each related field. You can override it in your `SoftDeleteObject` subclass to call it only if on_delete for field is set to CASCADE:
    ```python
        def _do_delete(self, changeset, related):
            if related.on_delete is models.CASCADE:
                super()._do_delete(changeset, related)
            else:
                # do something smart here
    ```
    It seems reasonable to add support for other on_delete values (PROTECT, SET_NULL, SET_DEFAULT etc.), and possibly do that in main subclass, which will be subclassed by all your models.
2. `_do_delete()` will first try calling `getattr(self, rel).all().delete(changeset=changeset)` (or `getattr(self, rel).delete(changeset=changeset)`, for one-to-one fields). Your related field could use custom manager that would override `.delete()` call, and not proceed with deletion when `changeset` keyword argument is present.

There are also `undelete()` and `_do_undelete()` methods, that probably should be overridden to revert operation done during deletion. That seems non-trivial for anything but DO_NOTHING.

**Closed** 2022-05-30 10:56 UTC
